
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/credify.one/services/common/crypto
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Crypto_FRAMEWORK_H__
#define __Crypto_FRAMEWORK_H__

#include "Crypto.objc.h"
#include "Universe.objc.h"

#endif
